package co.uk.ocelotcr.Items;

public enum ItemList {

    COMMON_ASSAULT,
    EPIC_ASSAULT,
    LEGENDARY_ASSAULT,
    RARE_ASSAULT,
    UNCOMMON_ASSAULT,
    HEAVY_BULLET,
    LIGHT_BULLET,
    MEDIUM_BULLET,
    ROCKET_BULLET,
    SHELL_BULLET,
    TRAP,
    MINI_SHIELD,
    LARGE_SHIELD,
    HUGE_SHIELD,
    BANDAGE,
    MEDICAL_KIT;

}
